<div class="aside aside_flux" id="aside_flux">
	<a class="toggle_aside" href="#close"><i class="icon i_close"></i></a>

	<ul class="categories">
	<!-- Placez cette balise où vous souhaitez faire apparaître le gadget Bouton +1. -->
<div class="g-plusone" data-size="small"></div>

<!-- Placez cette ballise après la dernière balise Bouton +1. -->
<script type="text/javascript">
  window.___gcfg = {lang: 'fr'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
	<a href="https://twitter.com/demandetn" class="twitter-follow-button" data-show-count="false">Follow @demandeTN</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
		<?php if (!login_is_conf ($this->conf) || is_logged ()) { ?>
		<li>
			<div class="stick">
				<a class="btn btn-important" href="<?php echo _url ('configure', 'feed'); ?>"><?php echo Translate::t ('subscription_management'); ?></a>
				<a class="btn btn-important" href="<?php echo _url ('configure', 'categorize'); ?>"><i class="icon i_category"></i></a>
			</div>
		</li>
		<?php } elseif (login_is_conf ($this->conf)) { ?>
		<?php } ?>

		<li>
			<div class="category all">
				<a data-unread="<?php echo $this->nb_not_read; ?>" class="btn<?php echo $this->get_c == 'all' ? ' active' : ''; ?>" href="<?php echo _url ('index', 'index'); ?>">
					<i class="icon i_all"></i>
					<?php echo Translate::t ('all_feeds', $this->nb_total); ?>
				</a>
			</div>
		</li>

		

		<?php foreach ($this->cat_aside as $cat) { ?>
		<?php $feeds = $cat->feeds (); ?>
		<?php if (!empty ($feeds)) { ?>
		<li>
			<?php $c_active = false; if ($this->get_c == $cat->id ()) { $c_active = true; } ?>
			<div class="category stick<?php echo $c_active ? ' active' : ''; ?>">
				<a data-unread="<?php echo $cat->nbNotRead (); ?>" class="btn<?php echo $c_active ? ' active' : ''; ?>" href="<?php echo _url ('index', 'index', 'get', 'c_' . $cat->id ()); ?>">
					<?php echo htmlspecialchars($cat->name (), ENT_NOQUOTES, 'UTF-8'); ?>
				</a>
				<a class="btn dropdown-toggle" href="#"><i class="icon <?php echo $c_active ? 'i_up' : 'i_down'; ?>"></i></a>
			</div>

			<ul class="feeds<?php echo $c_active ? ' active' : ''; ?>">
				<?php foreach ($feeds as $feed) {
						$feed_id = $feed->id (); $nbEntries = $feed->nbEntries ();
						$f_active = ($this->get_f == $feed_id);
				?>
				<li id="f_<?php echo $feed_id; ?>" class="item<?php echo $f_active ? ' active' : ''; ?><?php echo $feed->inError () ? ' error' : ''; ?><?php echo $nbEntries == 0 ? ' empty' : ''; ?>">
					<div class="dropdown">
						<div class="dropdown-target"></div>
						<a class="dropdown-toggle" data-fweb="<?php echo $feed->website (); ?>"><i class="icon i_configure"></i></a>
<?php /* feed_config_template */ ?>
					</div>
					<img class="favicon" src="<?php echo $feed->favicon (); ?>" alt="✇" />
					<a class="feed" data-unread="<?php echo $feed->nbNotRead (); ?>" data-priority="<?php echo $feed->priority (); ?>" href="<?php echo _url ('index', 'index', 'get', 'f_' . $feed_id); ?>"><?php echo htmlspecialchars($feed->name(), ENT_NOQUOTES, 'UTF-8'); ?></a>
				</li>
				<?php } ?>
			</ul>
		</li>
		<?php } } ?>
	</ul>

	<span class="aside_flux_ender"> <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- demande_side_bar -->
<ins class="adsbygoogle"
     style="display:inline-block;width:250px;height:250px"
     data-ad-client="ca-pub-3944222927856458"
     data-ad-slot="1008380105"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

<iframe src="https://docs.google.com/forms/d/1nuy8DkAF7oqHHwWX7KosSmy_yF-gNk16D3whMYUrtGA/viewform?embedded=true" width="250" height="167" frameborder="0" marginheight="0" marginwidth="0">Chargement en cours...</iframe>
<a href="mailto:oussemos@gmail.com">   Contact Me</a>
</span>
	
</div>


<script id="feed_config_template" type="text/html">
	<ul class="dropdown-menu">
		<li class="dropdown-close"><a href="#close">&nbsp;</a></li>
		<li class="item"><a href="<?php echo _url ('index', 'index', 'get', 'f_!!!!!!'); ?>"><?php echo Translate::t ('filter'); ?></a></li>
		<li class="item"><a target="_blank" href="http://example.net/"><?php echo Translate::t ('see_website'); ?></a></li>
		<?php if (!login_is_conf ($this->conf) || is_logged ()) { ?>
		<li class="separator"></li>
		<li class="item"><a href="<?php echo _url ('configure', 'feed', 'id', '!!!!!!'); ?>"><?php echo Translate::t ('administration'); ?></a></li>
		<li class="item"><a href="<?php echo _url ('feed', 'actualize', 'id', '!!!!!!'); ?>"><?php echo Translate::t ('actualize'); ?></a></li>
		<li class="item"><a href="<?php echo _url ('entry', 'read', 'is_read', 1, 'get', 'f_!!!!!!'); ?>"><?php echo Translate::t ('mark_read'); ?></a></li>
		<?php } ?>
	</ul>
</script>
